name: "Publish Release"
on:
  push:
    tags:
      - '*'
jobs:
  build-and-publush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0

      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"

      - name: "Build with Gradle"
        id: build
        run: "chmod +x gradlew && ./gradlew build"

      - name: "Get Version"
        id: version
        run: echo "VERSION_INFORMATION=$(${{github.workspace}}/gradlew -q showVersion)" >> $GITHUB_ENV

      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name: "swarmsmps2-${{ env.VERSION_INFORMATION }}.jar"
          path: "build/libs/swarmsmps2-${{ env.VERSION_INFORMATION }}.jar"

      - name: "Upload to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: "build/libs/swarmsmps2-${{ env.VERSION_INFORMATION }}.jar"
          game_endpoint: "minecraft"
          game_versions: "7498,9639,96389008"
          project_id: "916645"
          token: "${{ secrets.CF_API_KEY }}"
